# Methods = nearest, heuristic, plane, pcl
method: nearest

# true for calibration mode, false for scan odometry mode 
calibrate: true

in_scan_topic_front: /scan_front
in_scan_topic_back: /scan_rear

#icp 
# maximum_iterations: 100
# euclidean_fitness_epsilon: 1.0e-10
# transformation_epsilon: 1.0e-12
# max_correspondence_distance: 0.5

maximum_iterations: 100
euclidean_fitness_epsilon: 1.0e-12
transformation_epsilon: 1.0e-15
max_correspondence_distance: 0.05

##for heuristic
#in degree
max_correspondence_angle: 130